=== liuhozz/student/HighOrder/Dom4j/bin/user.dtd
<?xml version="1.0" encoding="UTF-8"?>
	<!ELEMENT users (user)+>
	<!ELEMENT user (name,age,sail)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT age (#PCDATA)>
	<!ELEMENT sail (#PCDATA)>

=== liuhozz/student/HighOrder/Dom4j/bin/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "user.dtd">
<users>
	<user>
		<name>张三</name>
		<age>23</age>
		<sail>12k</sail>
	</user>
	
	
	<user>
		<name>李四</name>
		<age>24</age>
		<sail>15k</sail>
	</user>

</users>
